FinalProject/Controllers/BrandController.cs
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Context;
using FinalProject.Context.Models;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalProject.Controllers
{
    public class BrandController:Controller
    {
        private readonly AppDbContext _context;

        public BrandController(AppDbContext context)
        {
            _context = context;
        }

        
        public async Task<IActionResult> GetAll()
        {
            var brands = await _context.Brands.Select(x => new BrandViewModel(){Id = x.Id,Name = x.Name}).ToListAsync();
            
            return View(brands);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateBrandViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var brand = new Brand{Name = model.Name};
            await _context.Brands.AddAsync(brand);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }

            EditBrandViewModel model = new EditBrandViewModel(){Id = brand.Id, Name = brand.Name};
            
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(EditBrandViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var brand = await _context.Brands.FindAsync(model.Id);
            if (brand == null)
            {
                return NotFound();
            }

            brand.Name = model.Name;

            await _context.SaveChangesAsync();
            
            return RedirectToAction("GetAll");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var brand = await _context.Brands.FindAsync(id);

            //_context.Entry(brand).State = EntityState.Deleted;
            _context.Brands.Remove(brand);

            await _context.SaveChangesAsync();
            
            return RedirectToAction("GetAll");
        }
        
    }
}

FinalProject/Controllers/CarController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Context;
using FinalProject.Context.Models;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalProject.Controllers
{
    public class CarController:Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public CarController(AppDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public async Task<IActionResult> Create()
        {
            var model = new CreateCarViewModel
            {
                Brands = await _context.Brands.Select(x => new BrandViewModel {Id = x.Id, Name = x.Name}).ToListAsync(),
                FuelTypes = await _context.FuelTypes.ToDictionaryAsync(x => x.Id, x => x.Name),
                Categories = await _context.Categories.Select(x => new CategoryViewModel {Id = x.Id, Name = x.Name})
                    .ToListAsync(),
                Cities = await _context.Cities.Select(x => new CityViewModel {Id = x.Id, Name = x.Name}).ToListAsync(),
                BodyTypes = await _context.BodyTypes.ToDictionaryAsync(x=>x.Id, x=>x.Name)
            };
            
            
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCarViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Brands = await _context.Brands.Select(x => new BrandViewModel {Id = x.Id, Name = x.Name})
                    .ToListAsync();
                model.FuelTypes = await _context.FuelTypes.ToDictionaryAsync(x => x.Id, x => x.Name);
                model.Categories = await _context.Categories
                    .Select(x => new CategoryViewModel {Id = x.Id, Name = x.Name})
                    .ToListAsync();
                model.Cities = await _context.Cities.Select(x => new CityViewModel {Id = x.Id, Name = x.Name})
                    .ToListAsync();
                model.BodyTypes = await _context.BodyTypes.ToDictionaryAsync(x => x.Id, x => x.Name);
                return View(model);
            }

            #region adding file
            if (model.Image != null)
            {
                string dirPath = _environment.WebRootPath + "/images";
                if (!Directory.Exists(dirPath))
                {
                    Directory.CreateDirectory(dirPath);
                }

                string imagePath = dirPath + $"/{model.Image.FileName}";

                if (!System.IO.File.Exists(imagePath))
                {
                    using (FileStream fs = new FileStream(imagePath, FileMode.Create))
                    {
                        await model.Image.CopyToAsync(fs);
                    }
                }
            }
            #endregion

            var car = new Car
            {
                BrandId = model.BrandId,
                CategoryId = model.CategoryId,
                Doors = model.Doors,
                Model = model.ModelName,
                Passengers = model.Passengers,
                BaggageCount = model.BaggageCount,
                CanDeparture = model.CanDeparture,
                DailyPrice = model.DailyPrice,
                FromAge = model.FromAge,
                ImagePath = model.Image != null ? $"/images/{model.Image.FileName}" : null,
                EngineVolume = model.EngineVolume,
                HasConditioning = model.HasConditioning,
                IsFree = model.IsFree,
                IsManual = model.IsManual,
                TilAge = model.TilAge,
                RequiredMileage = model.RequiredMileage,
                BodyTypeId = model.BodyTypeId
            };

            await _context.Cars.AddAsync(car);
            await _context.SaveChangesAsync();

            foreach (var i in model.FuelTypesId)
            {
                await _context.CarFuelTypes.AddAsync(new CarFuelType {CarId = car.Id, FuelTypeId = i});
            }
            
            foreach (var i in model.CitiesId)
            {
                await _context.CarCities.AddAsync(new CarCity {CarId = car.Id, CityId = i});
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("GetAll");
        }

        
        [Authorize]
        public async Task<IActionResult> GetAll(int cityId, int fuelTypeId,int categoryId)
        {
            var carsViewModel = new GetAllCarsViewModel
            {
                Cars = await _context.Cars
                    .Include(x => x.CarCities).ThenInclude(x => x.City)
                    .Include(x => x.CarFuelTypes).ThenInclude(x => x.FuelType)
                    .Where(x => (cityId == 0 || x.CarCities.Select(c => c.CityId).Contains(cityId))
                                && (fuelTypeId == 0 || x.CarFuelTypes.Select(f => f.FuelTypeId).Contains(fuelTypeId))
                                && (categoryId == 0 || x.CategoryId == categoryId))
                    .Include(x => x.Brand)
                    .Include(x => x.Category)
                    .Include(x => x.BodyType)
                    .Select(x => new CarViewModel()
                    {
                        Id = x.Id,
                        Doors = x.Doors,
                        Model = x.Model,
                        Passengers = x.Passengers,
                        BaggageCount = x.BaggageCount,
                        BrandName = x.Brand.Name,
                        CanDeparture = x.CanDeparture,
                        CategoryName = x.Category.Name,
                        DailyPrice = x.DailyPrice,
                        EngineVolume = x.EngineVolume,
                        FromAge = x.FromAge,
                        HasConditioning = x.HasConditioning,
                        ImagePath = x.ImagePath,
                        IsFree = x.IsFree,
                        IsManual = x.IsManual,
                        RequiredMileage = x.RequiredMileage,
                        TilAge = x.TilAge,
                        BodyTypeName = x.BodyType.Name,
                        Cities = x.CarCities.Select(c => c.City.Name).ToList(),
                        FuelTypes = x.CarFuelTypes.Select(f => f.FuelType.Name).ToList()
                    }).ToListAsync(),
                Cities = await _context.Cities.Select(x => new CityViewModel {Id = x.Id, Name = x.Name}).ToListAsync(),
                FuelTypes = await _context.FuelTypes.ToDictionaryAsync(x => x.Id, x => x.Name),
                Categories = await _context.Categories.Select(x => new CategoryViewModel {Id = x.Id, Name = x.Name})
                    .ToListAsync()
            };
            
            return View(carsViewModel);
        }
        
        

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var car = await _context.Cars.FindAsync(id);

            var carFuelTypes = await _context.CarFuelTypes.Where(x => x.CarId == id).ToListAsync();

            var carCities = await _context.CarCities.Where(x => x.CarId == id).ToListAsync();
            
            _context.CarFuelTypes.RemoveRange(carFuelTypes);
            _context.CarCities.RemoveRange(carCities);
            _context.Cars.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction("GetAll");
        }

        
        
        public async Task<IActionResult> Edit(int id)
        {
            var car = await _context.Cars.FindAsync(id);


            var model = new EditCarViewModel()
            {
                BrandId = car.BrandId,
                CategoryId = car.CategoryId,
                Doors = car.Doors,
                ModelName = car.Model,
                Passengers = car.Passengers,
                BaggageCount = car.BaggageCount,
                CanDeparture = car.CanDeparture,
                DailyPrice = car.DailyPrice,
                FromAge = car.FromAge,
                EngineVolume = car.EngineVolume,
                HasConditioning = car.HasConditioning,
                IsFree = car.IsFree,
                IsManual = car.IsManual,
                TilAge = car.TilAge,
                RequiredMileage = car.RequiredMileage,
                BodyTypeId = car.BodyTypeId,
                Brands = await _context.Brands.Select(x => new BrandViewModel {Id = x.Id, Name = x.Name}).ToListAsync(),
                FuelTypes = await _context.FuelTypes.ToDictionaryAsync(x => x.Id, x => x.Name),
                Categories = await _context.Categories.Select(x => new CategoryViewModel {Id = x.Id, Name = x.Name})
                    .ToListAsync(),
                Cities = await _context.Cities.Select(x => new CityViewModel {Id = x.Id, Name = x.Name}).ToListAsync(),
                BodyTypes = await _context.BodyTypes.ToDictionaryAsync(x=>x.Id, x=>x.Name),
                CitiesId = await _context.CarCities.Where(x=>x.CarId == car.Id).Select(x=>x.CityId).ToListAsync(),
                FuelTypesId = await _context.CarFuelTypes.Where(x=>x.CarId == car.Id).Select(x=>x.FuelTypeId).ToListAsync(),
                Id = id
            };
            return View(model);
        }
        
        
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(EditCarViewModel model)
        {
            var car = await _context.Cars.FindAsync(model.Id);

            car.BrandId = model.BrandId;
            car.CategoryId = model.CategoryId;
            car.Doors = model.Doors;
            car.Model = model.ModelName;
            car.Passengers = model.Passengers;
            car.BaggageCount = model.BaggageCount;
            car.CanDeparture = model.CanDeparture;

FinalProject/Controllers/CityController.cs
using System.Linq;
using System.Threading.Tasks;
using FinalProject.Context;
using FinalProject.Context.Models;
using FinalProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalProject.Controllers
{
    public class CityController:Controller
    {
        private readonly AppDbContext _context;

        public CityController(AppDbContext context)
        {
            _context = context;
        }
        
        
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetAll()
        {
            var cities = await _context.Cities.Select(x => new CityViewModel(){Id = x.Id,Name = x.Name}).ToListAsync();
            
            return View(cities);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCityViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var city = new City(){Name = model.Name};
            await _context.Cities.AddAsync(city);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var city = await _context.Cities.FindAsync(id);
            if (city == null)
            {
                return NotFound();
            }

            EditCityViewModel model = new EditCityViewModel(){Id = city.Id, Name = city.Name};
            
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(EditCityViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var city = await _context.Cities.FindAsync(model.Id);
            if (city == null)
            {
                return NotFound();
            }

            city.Name = model.Name;

            await _context.SaveChangesAsync();
            
            return RedirectToAction("GetAll");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var city = await _context.Cities.FindAsync(id);
            
            _context.Cities.Remove(city);

            await _context.SaveChangesAsync();
            
            return RedirectToAction("GetAll");
        }
    }
}

FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FinalProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalProject</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="GetAll">Машины</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Create">Добавить Марку</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="GetAll">Марки Авто</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Create">Добавить Авто</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="GetAll">Список Авто</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Create">Добавить Категорию</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="GetAll">Список категориев</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Create">Добавить Город</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="GetAll">Список Городов</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetAllForAdmin">Список Заявок</a>
                            </li>
                        }
                        
                        if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetAll">Список Заявок</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="GetAll">Забронированно</a>
                            </li> 
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выход</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>